# File: src/urban_air_quality_digital_twin/config/tasks.yaml
# Description: CrewAI task orchestration for Urban Air Quality Digital Twin

tasks:
  - name: FetchData
    agent: DataCollector
    tool: data_fetcher
    description: Fetch real-time air quality and weather data for all configured cities and store in data/raw/.

  - name: PreprocessData
    agent: DataCollector
    tool: preprocess
    description: Clean, normalize, and preprocess raw data, saving results to data/processed/.

  - name: PredictAirQuality
    agent: Predictor
    tool: prediction
    description: Generate air quality forecasts and scenario analyses using processed data, saving results to data/processed/.

  - name: ServeData
    agent: DataCollector
    tool: data_server
    description: Expose processed and predicted data for dashboard/UI access via files or API endpoints.
